/*
SQLyog Community v13.1.5  (64 bit)
MySQL - 5.7.26 : Database - seminario1
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`seminario1` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `seminario1`;

/*Table structure for table `avatar` */

DROP TABLE IF EXISTS `avatar`;

CREATE TABLE `avatar` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `componente` varchar(255) DEFAULT NULL,
  `nombre_original` varchar(255) DEFAULT NULL,
  `nombre_traducido` varchar(255) DEFAULT NULL,
  `activo` tinyint(1) DEFAULT NULL,
  KEY `id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=317 DEFAULT CHARSET=latin1;

/*Data for the table `avatar` */

insert  into `avatar`(`id`,`componente`,`nombre_original`,`nombre_traducido`,`activo`) values 
(4,'estilo_avatar','Circle','Redondo',1),
(5,'estilo_avatar','Transparent','Trasparente',1),
(6,'cabeza','NoHair','SinPelo',1),
(7,'cabeza','Eyepatch','Parche',1),
(8,'cabeza','Hat','Sombrero',1),
(9,'cabeza','Hijab','Hijab',1),
(10,'cabeza','Turban','Turbante',1),
(11,'cabeza','WinterHat1','GorroInvernal1',1),
(12,'cabeza','WinterHat2','GorroInvernal2',1),
(13,'cabeza','WinterHat3','GorroInvernal3',1),
(14,'cabeza','WinterHat4','GorroInvernal4',1),
(15,'cabeza','LongHairBigHair','PeloLargoVoluminoso',1),
(16,'cabeza','LongHairBob ','PeloLargoBob',1),
(17,'cabeza','LongHairBun','Rodete',1),
(18,'cabeza','LongHairCurly','PeloLargoEnrulado',1),
(19,'cabeza','LongHairCurvy','PeloLargoOndas',1),
(20,'cabeza','LongHairDreads','Rastas',1),
(21,'cabeza','LongHairFrida','FridaKahlo',1),
(22,'cabeza','LongHairFro','Afro',1),
(23,'cabeza','LongHairFroBand','AfroVincha',1),
(24,'cabeza','LongHairNotTooLong','PeloMediaMelena',1),
(25,'cabeza','LongHairShavedSides','PeloLargoCostadosRapados',1),
(26,'cabeza','LongHairMiaWallace','CorteMiaWallace',1),
(27,'cabeza','LongHairStraight','PeloLargoLasio',1),
(28,'cabeza','LongHairStraight2','PeloLargoLasio2',1),
(29,'cabeza','LongHairStraightStrand','PeloLargoLasioMechones',1),
(30,'cabeza','ShortHairDreads1','PeloCortoRastas1',1),
(31,'cabeza','ShortHairDreads2','PeloCortoRastas2',1),
(32,'cabeza','ShortHairFrizzle','PeloCortoEncrespado',1),
(33,'cabeza','ShortHairShaggyMullet','CorteShaggyMullet',1),
(34,'cabeza','ShortHairShortCurly','PeloCortoEnrulado',1),
(35,'cabeza','ShortHairShortFlat','PeloCortoPlano',1),
(36,'cabeza','ShortHairShortRound','PeloCortoRedondeado',1),
(37,'cabeza','ShortHairShortWaved','PeloCortoOndulado',1),
(38,'cabeza','ShortHairSides','PeloALosCostados',1),
(39,'cabeza','ShortHairTheCaesar','CorteTheCaesar',1),
(40,'cabeza','ShortHairTheCaesarSidePart','CorteTheCaesarConRaya',1),
(41,'accesorios','Blank','Vacio',1),
(42,'accesorios','Kurt','LentesDeSolKurtCobain',1),
(43,'accesorios','Prescription01','Anteojos01',1),
(44,'accesorios','Prescription02','Anteojos02',1),
(45,'accesorios','Round','AnteojosHarryPotter',1),
(46,'accesorios','SunGlasses','LentesDeSol',1),
(47,'accesorios','Wayfarers','LentesDeSolRayBan',1),
(48,'colorSombrero','Black','Negro',1),
(49,'colorSombrero','Blue01','Azul01',1),
(50,'colorSombrero','Blue02','Azul02',1),
(51,'colorSombrero','Blue03','Azul03',1),
(52,'colorSombrero','Gray01','Gris01',1),
(53,'colorSombrero','Gray02','Gris02',1),
(54,'colorSombrero','Heather','Gris03',1),
(55,'colorSombrero','PastelBlue','AzulPastel',1),
(56,'colorSombrero','PastelGreen','VerdePastel',1),
(57,'colorSombrero','PastelOrange','NaranjaPastel',1),
(58,'colorSombrero','PastelRed','RojoPastel',1),
(59,'colorSombrero','PastelYellow','AmarilloPastel',1),
(60,'colorSombrero','Pink','Rosa',1),
(61,'colorSombrero','Red','Rojo',1),
(62,'colorSombrero','White','Blanco',1),
(63,'colorPelo','Auburn','Bermejo',1),
(64,'colorPelo','Black','Negro',1),
(65,'colorPelo','Blonde','Rubio',1),
(66,'colorPelo','BlondeGolden','RubioDorado',1),
(67,'colorPelo','Brown','Casta&ntilde;o',1),
(68,'colorPelo','BrownDark','Casta&ntilde;oOscuro',1),
(69,'colorPelo','PastelPink','RosaPastel',1),
(70,'colorPelo','Platinum','Platinado',1),
(71,'colorPelo','Red','Rojo',1),
(72,'colorPelo','SilverGray','GrisPlata',1),
(73,'barba','Blanck','Rasurado',1),
(74,'barba','BeardMedium','BarbaMedia',1),
(75,'barba','BeardLight','BarbaTenue',1),
(76,'barba','BeardMagestic','BarbaMagestuosa',1),
(77,'barba','MoustacheFancy','MostachoFrances',1),
(78,'barba','MoustacheMagnum','MostachoMagnum',1),
(79,'colorBarba','Auburn','Bermejo',1),
(80,'colorBarba','Black','Negro',1),
(81,'colorBarba','Blonde','Rubio',1),
(82,'colorBarba','BlondeGolden','RubioDorado',1),
(83,'colorBarba','Brown','Casta&ntilde;o',1),
(84,'colorBarba','BrownDark','Casta&ntilde;oOscuro',1),
(85,'colorBarba','PastelPink','RosaPastel',1),
(86,'colorBarba','Platinum','Platinado',1),
(87,'colorBarba','Red','Rojo',1),
(88,'atuendos','BlazerShirt','RemeraConSaco',1),
(89,'atuendos','BlazerSweater','PuloverConSaco',1),
(90,'atuendos','CollarSweater','PuloverConCuello',1),
(91,'atuendos','GraphicShirt','RemeraEstampada',1),
(92,'atuendos','Hoodie','Cangurito',1),
(93,'atuendos','Overall','Enterito',1),
(94,'atuendos','ShirtCrewNeck','RemeraCuelloRedondo',1),
(95,'atuendos','ShirtScoopNeck','RemeraCuelloRedondoAbierto',1),
(96,'atuendos','ShirtVNeck','RemeraCuelloEnV',1),
(97,'colorTela','Black','Negro',1),
(98,'colorTela','Blue01','Azul01',1),
(99,'colorTela','Blue02','Azul02',1),
(100,'colorTela','Blue03','Azul03',1),
(101,'colorTela','Gray01','Gris01',1),
(102,'colorTela','Gray02','Gris02',1),
(103,'colorTela','Heather','Gris03',1),
(104,'colorTela','PastelBlue','AzulPastel',1),
(105,'colorTela','PastelGreen','VerdePastel',1),
(106,'colorTela','PastelOrange','NaranjaPastel',1),
(107,'colorTela','PastelRed','RojoPastel',1),
(108,'colorTela','PastelYellow','AmarilloPastel',1),
(109,'colorTela','Pink','Rosa',1),
(110,'colorTela','Red','Rojo',1),
(111,'colorTela','White','Blanco',1),
(112,'ojos','Close','Cerrados',1),
(113,'ojos','Cry','Llorando',1),
(114,'ojos','Default','PorDefecto',1),
(115,'ojos','Dizzy','EnCruz',1),
(116,'ojos','EyeRoll','RodarOjos',1),
(117,'ojos','Happy','Feliz',1),
(118,'ojos','Hearts','Corazones',1),
(119,'ojos','Side','Picaro',1),
(120,'ojos','Squint','Entrecerrados',1),
(121,'ojos','Surprised','Sorprendido',1),
(122,'ojos','Wink','Gui&ntilde;o1',1),
(123,'ojos','WinkWacky','Gui&ntilde;o2',1),
(124,'cejas','Angry','Enojado1',1),
(125,'cejas','AngryNatural','Enojado2',1),
(126,'cejas','Default','PorDefecto1',1),
(127,'cejas','DefaultNatural','PorDefecto2',1),
(128,'cejas','FlatNatural','Chatas',1),
(129,'cejas','RaisedExcited','Elevadas1',1),
(130,'cejas','RaisedExcitedNatural','Elevadas2',1),
(131,'cejas','SadConcerned','TristePreocupado1',1),
(132,'cejas','SadConcernedNatural','TristePreocupado2',1),
(133,'cejas','UnibrowNatural','Uniceja',1),
(134,'cejas','UpDown','UnaCejaElevada1',1),
(135,'cejas','UpDownNatural','UnaCejaElevada2',1),
(136,'boca','Concerned','Preocupado',1),
(137,'boca','Default','PorDefecto',1),
(138,'boca','Disbelief','Boquiabierto',1),
(139,'boca','Eating','Sonrojado',1),
(140,'boca','Grimace','Mueca',1),
(141,'boca','Sad','Triste',1),
(142,'boca','ScreamOpen','Asustado',1),
(143,'boca','Serious','Serio',1),
(144,'boca','Smile','SonrisaDientes',1),
(145,'boca','Tongue','Lengua',1),
(146,'boca','Twinkie','Sonrisa',1),
(147,'boca','Vomit','Vomito',1),
(148,'piel','Tanned','Bronceado',1),
(149,'piel','Yellow','Amarillenta',1),
(150,'piel','Pale','Palido',1),
(151,'piel','Light','Claro',1),
(152,'piel','Brown','Moreno',1),
(153,'piel','DarkBrown','MorenoOscuro1',1),
(154,'piel','Black','MorenoOscuro2',1),
(155,'estilo_avatar','Circle','Redondo',1),
(156,'estilo_avatar','Transparent','Trasparente',1),
(157,'cabeza','NoHair','SinPelo',1),
(158,'cabeza','Eyepatch','Parche',1),
(159,'cabeza','Hat','Sombrero',1),
(160,'cabeza','Hijab','Hijab',1),
(161,'cabeza','Turban','Turbante',1),
(162,'cabeza','WinterHat1','GorroInvernal1',1),
(163,'cabeza','WinterHat2','GorroInvernal2',1),
(164,'cabeza','WinterHat3','GorroInvernal3',1),
(165,'cabeza','WinterHat4','GorroInvernal4',1),
(166,'cabeza','LongHairBigHair','PeloLargoVoluminoso',1),
(167,'cabeza','LongHairBob ','PeloLargoBob',1),
(168,'cabeza','LongHairBun','Rodete',1),
(169,'cabeza','LongHairCurly','PeloLargoEnrulado',1),
(170,'cabeza','LongHairCurvy','PeloLargoOndas',1),
(171,'cabeza','LongHairDreads','Rastas',1),
(172,'cabeza','LongHairFrida','FridaKahlo',1),
(173,'cabeza','LongHairFro','Afro',1),
(174,'cabeza','LongHairFroBand','AfroVincha',1),
(175,'cabeza','LongHairNotTooLong','PeloMediaMelena',1),
(176,'cabeza','LongHairShavedSides','PeloLargoCostadosRapados',1),
(177,'cabeza','LongHairMiaWallace','CorteMiaWallace',1),
(178,'cabeza','LongHairStraight','PeloLargoLasio',1),
(179,'cabeza','LongHairStraight2','PeloLargoLasio2',1),
(180,'cabeza','LongHairStraightStrand','PeloLargoLasioMechones',1),
(181,'cabeza','ShortHairDreads1','PeloCortoRastas1',1),
(182,'cabeza','ShortHairDreads2','PeloCortoRastas2',1),
(183,'cabeza','ShortHairFrizzle','PeloCortoEncrespado',1),
(184,'cabeza','ShortHairShaggyMullet','CorteShaggyMullet',1),
(185,'cabeza','ShortHairShortCurly','PeloCortoEnrulado',1),
(186,'cabeza','ShortHairShortFlat','PeloCortoPlano',1),
(187,'cabeza','ShortHairShortRound','PeloCortoRedondeado',1),
(188,'cabeza','ShortHairShortWaved','PeloCortoOndulado',1),
(189,'cabeza','ShortHairSides','PeloALosCostados',1),
(190,'cabeza','ShortHairTheCaesar','CorteTheCaesar',1),
(191,'cabeza','ShortHairTheCaesarSidePart','CorteTheCaesarConRaya',1),
(192,'accesorios','Blank','Vacio',1),
(193,'accesorios','Kurt','LentesDeSolKurtCobain',1),
(194,'accesorios','Prescription01','Anteojos01',1),
(195,'accesorios','Prescription02','Anteojos02',1),
(196,'accesorios','Round','AnteojosHarryPotter',1),
(197,'accesorios','SunGlasses','LentesDeSol',1),
(198,'accesorios','Wayfarers','LentesDeSolRayBan',1),
(199,'colorSombrero','Black','Negro',1),
(200,'colorSombrero','Blue01','Azul01',1),
(201,'colorSombrero','Blue02','Azul02',1),
(202,'colorSombrero','Blue03','Azul03',1),
(203,'colorSombrero','Gray01','Gris01',1),
(204,'colorSombrero','Gray02','Gris02',1),
(205,'colorSombrero','Heather','Gris03',1),
(206,'colorSombrero','PastelBlue','AzulPastel',1),
(207,'colorSombrero','PastelGreen','VerdePastel',1),
(208,'colorSombrero','PastelOrange','NaranjaPastel',1),
(209,'colorSombrero','PastelRed','RojoPastel',1),
(210,'colorSombrero','PastelYellow','AmarilloPastel',1),
(211,'colorSombrero','Pink','Rosa',1),
(212,'colorSombrero','Red','Rojo',1),
(213,'colorSombrero','White','Blanco',1),
(214,'colorPelo','Auburn','Bermejo',1),
(215,'colorPelo','Black','Negro',1),
(216,'colorPelo','Blonde','Rubio',1),
(217,'colorPelo','BlondeGolden','RubioDorado',1),
(218,'colorPelo','Brown','Casta&ntilde;o',1),
(219,'colorPelo','BrownDark','Casta&ntilde;oOscuro',1),
(220,'colorPelo','PastelPink','RosaPastel',1),
(221,'colorPelo','Platinum','Platinado',1),
(222,'colorPelo','Red','Rojo',1),
(223,'colorPelo','SilverGray','GrisPlata',1),
(224,'barba','Blanck','Rasurado',1),
(225,'barba','BeardMedium','BarbaMedia',1),
(226,'barba','BeardLight','BarbaTenue',1),
(227,'barba','BeardMagestic','BarbaMagestuosa',1),
(228,'barba','MoustacheFancy','MostachoFrances',1),
(229,'barba','MoustacheMagnum','MostachoMagnum',1),
(230,'colorBarba','Auburn','Bermejo',1),
(231,'colorBarba','Black','Negro',1),
(232,'colorBarba','Blonde','Rubio',1),
(233,'colorBarba','BlondeGolden','RubioDorado',1),
(234,'colorBarba','Brown','Casta&ntilde;o',1),
(235,'colorBarba','BrownDark','Casta&ntilde;oOscuro',1),
(236,'colorBarba','PastelPink','RosaPastel',1),
(237,'colorBarba','Platinum','Platinado',1),
(238,'colorBarba','Red','Rojo',1),
(239,'atuendos','BlazerShirt','RemeraConSaco',1),
(240,'atuendos','BlazerSweater','PuloverConSaco',1),
(241,'atuendos','CollarSweater','PuloverConCuello',1),
(242,'atuendos','GraphicShirt','RemeraEstampada',1),
(243,'atuendos','Hoodie','Cangurito',1),
(244,'atuendos','Overall','Enterito',1),
(245,'atuendos','ShirtCrewNeck','RemeraCuelloRedondo',1),
(246,'atuendos','ShirtScoopNeck','RemeraCuelloRedondoAbierto',1),
(247,'atuendos','ShirtVNeck','RemeraCuelloEnV',1),
(248,'colorTela','Black','Negro',1),
(249,'colorTela','Blue01','Azul01',1),
(250,'colorTela','Blue02','Azul02',1),
(251,'colorTela','Blue03','Azul03',1),
(252,'colorTela','Gray01','Gris01',1),
(253,'colorTela','Gray02','Gris02',1),
(254,'colorTela','Heather','Gris03',1),
(255,'colorTela','PastelBlue','AzulPastel',1),
(256,'colorTela','PastelGreen','VerdePastel',1),
(257,'colorTela','PastelOrange','NaranjaPastel',1),
(258,'colorTela','PastelRed','RojoPastel',1),
(259,'colorTela','PastelYellow','AmarilloPastel',1),
(260,'colorTela','Pink','Rosa',1),
(261,'colorTela','Red','Rojo',1),
(262,'colorTela','White','Blanco',1),
(263,'estampa','Bat','Murci&eacute;lago',1),
(264,'estampa','Cumbia','Cumbia',1),
(265,'estampa','Deer','Ciervo',1),
(266,'estampa','Diamond','Diamante',1),
(267,'estampa','Hola','Hola',1),
(268,'estampa','Pizza','Pizza',1),
(269,'estampa','Resist','Resist',1),
(270,'estampa','Selena','Selena',1),
(271,'estampa','Bear','Oso',1),
(272,'estampa','SkullOutLine','Calavera1',1),
(273,'estampa','Skull','Calavera2',1),
(274,'ojos','Close','Cerrados',1),
(275,'ojos','Cry','Llorando',1),
(276,'ojos','Default','PorDefecto',1),
(277,'ojos','Dizzy','EnCruz',1),
(278,'ojos','EyeRoll','RodarOjos',1),
(279,'ojos','Happy','Feliz',1),
(280,'ojos','Hearts','Corazones',1),
(281,'ojos','Side','Picaro',1),
(282,'ojos','Squint','Entrecerrados',1),
(283,'ojos','Surprised','Sorprendido',1),
(284,'ojos','Wink','Gui&ntilde;o1',1),
(285,'ojos','WinkWacky','Gui&ntilde;o2',1),
(286,'cejas','Angry','Enojado1',1),
(287,'cejas','AngryNatural','Enojado2',1),
(288,'cejas','Default','PorDefecto1',1),
(289,'cejas','DefaultNatural','PorDefecto2',1),
(290,'cejas','FlatNatural','Chatas',1),
(291,'cejas','RaisedExcited','Elevadas1',1),
(292,'cejas','RaisedExcitedNatural','Elevadas2',1),
(293,'cejas','SadConcerned','TristePreocupado1',1),
(294,'cejas','SadConcernedNatural','TristePreocupado2',1),
(295,'cejas','UnibrowNatural','Uniceja',1),
(296,'cejas','UpDown','UnaCejaElevada1',1),
(297,'cejas','UpDownNatural','UnaCejaElevada2',1),
(298,'boca','Concerned','Preocupado',1),
(299,'boca','Default','PorDefecto',1),
(300,'boca','Disbelief','Boquiabierto',1),
(301,'boca','Eating','Sonrojado',1),
(302,'boca','Grimace','Mueca',1),
(303,'boca','Sad','Triste',1),
(304,'boca','ScreamOpen','Asustado',1),
(305,'boca','Serious','Serio',1),
(306,'boca','Smile','SonrisaDientes',1),
(307,'boca','Tongue','Lengua',1),
(308,'boca','Twinkie','Sonrisa',1),
(309,'boca','Vomit','Vomito',1),
(310,'piel','Tanned','Bronceado',1),
(311,'piel','Yellow','Amarillenta',1),
(312,'piel','Pale','Palido',1),
(313,'piel','Light','Claro',1),
(314,'piel','Brown','Moreno',1),
(315,'piel','DarkBrown','MorenoOscuro1',1),
(316,'piel','Black','MorenoOscuro2',1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
